# Default values for Portask Helm chart (production-grade)

replicaCount: 3

image:
  repository: ghcr.io/meftunca/portask
  tag: "1.0.0"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

resources:
  limits:
    cpu: 2
    memory: 4Gi
  requests:
    cpu: 500m
    memory: 1Gi

affinity: {}
nodeSelector: {}
tolerations: []

persistence:
  enabled: true
  size: 10Gi
  storageClass: standard

env:
  - name: PORTASK_ENV
    value: production
  - name: PORTASK_LOG_LEVEL
    value: info

livenessProbe:
  httpGet:
    path: /healthz
    port: 8080
  initialDelaySeconds: 10
  periodSeconds: 10
  failureThreshold: 3

readinessProbe:
  httpGet:
    path: /readyz
    port: 8080
  initialDelaySeconds: 5
  periodSeconds: 5
  failureThreshold: 3
